# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: docker.2up.io/php7.4.2-cli:latest

# Select what we should cache between builds
cache:
  paths:
    - vendor/

# Define pipeline stages
stages:
  - prep
  - syntax
  - mess
  - tests
  - security

composer:
  stage: prep
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 1 days
    when: always
  only:
    refs:
      - master

phpcs:
  stage: syntax
  script:
    - ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php
  only:
    refs:
      - master

phpmd:
  stage: mess
  script:
    - ./vendor/phpmd/phpmd/src/bin/phpmd src/ text _phpmd/rules.xml
  only:
    refs:
      - master
  allow_failure: true

php-7.2:
  image: docker.2up.io/2up/php7.2-cli:latest
  stage: tests
  script:
    - echo "$HIBP_API_KEY" > api.key
    - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
  only:
    refs:
      - master

php-7.3:
  image: docker.2up.io/php7.3.14-cli:latest
  stage: tests
  script:
    - echo "$HIBP_API_KEY" > api.key
    - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
  only:
    refs:
      - master

php-7.4:
  image: docker.2up.io/php7.4.2-cli:latest
  stage: tests
  script:
    - echo "$HIBP_API_KEY" > api.key
    - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
  only:
    refs:
      - master

sensiolabs:
  stage: security
  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  only:
    refs:
      - master

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
#test:
#  script:
#  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
